<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?php echo $this->doctype() ?>
<html lang="en">
<head>
  <meta charset="utf-8">
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
  <!-- import CSS -->
  <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">

  <!-- Le styles -->
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/3rd/bootstrap.min.css'))
    ?>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="<?php echo $this->url('home') ?>">太初有道-圣经短歌</a>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="<?php echo $this->url('home') ?>">首页 <span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
    <?php echo $this->content ?>
  <hr>
  <footer>
    <p>&copy; <?php echo date('Y') ?> <a href="http://albertyu.com/">太初有道</a> 圣经短歌.</p>
  </footer>
</div>
<?php echo $this->inlineScript()
    ->prependFile($this->basePath('js/3rd/bootstrap.min.js'))
    ->prependFile($this->basePath('js/3rd/jquery-3.5.1.min.js')) ?>
<!-- import JavaScript -->
<script src="https://unpkg.com/element-ui/lib/index.js"></script>
</body>
</html>
